name: todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  piesocket_channels: ^2.0.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  firebase_core: ^3.4.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.4
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

